name: rc-select-backend-new
x-server: &base_server_setup
  build:
    context: ./
  # Used for python debugging.
  stdin_open: true
  tty: true
  environment: &base_server_environments
    DEBUG: ${DEBUG:-true}
    APP_ENVIRONMENT: ${APP_ENVIRONMENT:-DEV}
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?error}
    # Domain configs
    APP_DOMAIN: ${APP_DOMAIN:-http://localhost:8000}
    FRONTEND_DOMAIN: ${FRONTEND_DOMAIN:-http://localhost:3000}  # NOTE: Not used right now
    SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN:-localhost}
    CSRF_COOKIE_DOMAIN: ${CSRF_COOKIE_DOMAIN:-localhost}
    # Postgres
    POSTGRES_DB: ${POSTGRES_DB:-rc-select}
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    POSTGRES_HOST: ${POSTGRES_HOST:-db}
    POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    # Email
    EMAIL_HOST: ${EMAIL_HOST:-mailpit}
    EMAIL_PORT: ${EMAIL_PORT:-1025}
    EMAIL_HOST_USER: ${EMAIL_HOST_USER:-mailpit}
    EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD:-mailpit}
    DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL:-rc-select-dev@local.com}
    EMAIL_TO: ${EMAIL_TO:-test-rc-select-dev@local.com}
    #Celery
    CELERY_REDIS_URL: ${CELERY_REDIS_URL:-redis://redis:6379/0}
    CACHE_REDIS_URL: ${CACHE_REDIS_URL:-redis://redis:6379/1}
    TEST_CACHE_REDIS_URL: ${TEST_CACHE_REDIS_URL:-redis://redis:6379/11}

  env_file:
    - path: .env
      required: false
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./:/code/
    - ipython_data_local:/root/.ipython/profile_default   # persist ipython data, including ipython history
  depends_on:
    - db
    - redis
    - mailpit

x-worker: &base_worker_setup
  <<: *base_server_setup
  restart: unless-stopped
  environment:
    <<: *base_server_environments
    APP_TYPE: "WORKER"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rc-select}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data17:/var/lib/postgresql/data

  redis:
    image: redis:8
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
        - 8025:8025
    environment:
        MP_MAX_MESSAGES: 5000
        MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1

  web:
    <<: *base_server_setup
    command: ["/code/misc/dev/run_web.sh"]
    environment:
      <<: *base_server_environments
      APP_TYPE: "WEB"
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
      - redis

  worker:
    <<: *base_worker_setup
    command: bash -c "/code/misc/dev/run_worker.sh"
    healthcheck:
      test: ["CMD-SHELL", "celery -A main inspect ping -d celery@$$HOSTNAME || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  postgres_data17:
  ipython_data_local:
  mailpit_data:
  redis_data:
