name: rc-select-backend-new
x-server: &base_server_setup
  build:
    context: ./
  # Used for python debugging.
  stdin_open: true
  tty: true
  environment: &base_server_environments
    DEBUG: ${DEBUG:-true}
    ENABLE_DEBUG_TOOLBAR: ${ENABLE_DEBUG_TOOLBAR:-true}
    APP_ENVIRONMENT: ${APP_ENVIRONMENT:-DEV}
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?error}
    # Domain configs
    APP_DOMAIN: ${APP_DOMAIN:-http://localhost:8000}
    FRONTEND_DOMAIN: ${FRONTEND_DOMAIN:-http://localhost:3000}  # NOTE: Not used right now
    SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN:-localhost}
    CSRF_COOKIE_DOMAIN: ${CSRF_COOKIE_DOMAIN:-localhost}
    # Postgres
    POSTGRES_DB: ${POSTGRES_DB:-nrcs}
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    POSTGRES_HOST: ${POSTGRES_HOST:-db}
    POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  env_file:
    - path: .env
      required: false
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./:/code/
    - ipython_data_local:/root/.ipython/profile_default   # persist ipython data, including ipython history
  depends_on:
    - db

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: nrcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data17:/var/lib/postgresql/data

  web:
    <<: *base_server_setup
    command: ["/code/misc/dev/run_web.sh"]
    environment:
      <<: *base_server_environments
      APP_TYPE: "WEB"
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db

volumes:
  postgres_data17:
  ipython_data_local:
