name: nrcs-backend

services:
  web:
    command: ./deploy/run_prod.sh
    environment:
      DEBUG: ${DEBUG:-false}
      ENABLE_DEBUG_TOOLBAR: ${ENABLE_DEBUG_TOOLBAR:-false}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT:-PROD}
    volumes: !override
      - ./data/backend/media:/code/data/media
      - ./data/backend/static:/code/data/static
      - ipython_data_local:/root/.ipython/profile_default   # persist ipython data, including ipython history

  caddy:
    image: caddy:2
    restart: always
    volumes:
      # Caddy config
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      # Static files
      - ./data/backend:/app-assets/server-static:ro
      # Caddy data volumes
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CADDY_EMAIL: ${CADDY_EMAIL?err}
      CADDY_BACKEND_HOST: ${CADDY_BACKEND_HOST?err}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config:
