type AppEnumCollection {
  QuestionTypeEnum: [AppEnumCollectionQuestionTypeEnum!]!
  OrdinalTypeEnum: [AppEnumCollectionOrdinalTypeEnum!]!
}

type AppEnumCollectionOrdinalTypeEnum {
  key: OrdinalTypeEnum!
  label: String!
}

type AppEnumCollectionQuestionTypeEnum {
  key: QuestionTypeEnum!
  label: String!
}

input BoolBaseFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: Boolean

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [Boolean!]
}

"""Model representing case study of national society for specific tool."""
input CaseStudyFilter {
  id: ID
  AND: CaseStudyFilter
  OR: CaseStudyFilter
  NOT: CaseStudyFilter
  DISTINCT: Boolean
}

input CaseStudyOrder {
  id: Ordering
}

"""Model representing case study of national society for specific tool."""
type CaseStudyType {
  id: ID!
  title: String!
  toolId: ID!
  content: String!
  coverImage: DjangoFileType
}

type CaseStudyTypeOffsetPaginated {
  pageInfo: OffsetPaginationInfo!

  """Total count of existing results."""
  totalCount: Int!

  """List of paginated results."""
  results: [CaseStudyType!]!
}

"""Model representing catalog where a tool belongs to."""
input CatalogFilter {
  id: ID
  showInHelpMeChoose: BoolBaseFilterLookup
  AND: CatalogFilter
  OR: CatalogFilter
  NOT: CatalogFilter
  DISTINCT: Boolean
}

input CatalogOrder {
  id: Ordering
}

"""Model representing catalog where a tool belongs to."""
type CatalogType {
  id: ID!
  name: String!
  showInHelpMeChoose: Boolean!
  description: String!
  questions: [QuestionType!]!
}

type CatalogTypeOffsetPaginated {
  pageInfo: OffsetPaginationInfo!

  """Total count of existing results."""
  totalCount: Int!

  """List of paginated results."""
  results: [CatalogType!]!
}

"""Model representing option of checkbox question."""
type CheckboxOptionType {
  id: ID!
  questionId: ID!
  order: Int!
  text: String!
}

"""Model representing contact where anyone can react out to the admins."""
input ContactRequestFilter {
  id: ID
  AND: ContactRequestFilter
  OR: ContactRequestFilter
  NOT: ContactRequestFilter
  DISTINCT: Boolean
}

input ContactRequestOrder {
  id: Ordering
}

"""Model representing contact where anyone can react out to the admins."""
type ContactRequestType {
  id: ID!
  name: String!
  email: String!
  createdAt: DateTime!
  content: String
  nationalSociety: String!
}

type ContactRequestTypeOffsetPaginated {
  pageInfo: OffsetPaginationInfo!

  """Total count of existing results."""
  totalCount: Int!

  """List of paginated results."""
  results: [ContactRequestType!]!
}

"""Date with time (isoformat)"""
scalar DateTime

type DjangoFileType {
  name: String!
  size: Int!
  url: String!
}

input IDBaseFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: ID

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [ID!]
}

type OffsetPaginationInfo {
  offset: Int!
  limit: Int
}

input OffsetPaginationInput {
  offset: Int! = 0
  limit: Int
}

enum Ordering {
  ASC
  ASC_NULLS_FIRST
  ASC_NULLS_LAST
  DESC
  DESC_NULLS_FIRST
  DESC_NULLS_LAST
}

enum OrdinalTypeEnum {
  NOT_AVAILABLE
  ONE
  TWO
  THREE
  FOUR
}

type Query {
  catalog(id: ID!): CatalogType!
  tool(id: ID!): ToolType!
  catalogs(filters: CatalogFilter, order: CatalogOrder, pagination: OffsetPaginationInput): CatalogTypeOffsetPaginated!
  tools(filters: ToolFilter, order: ToolOrder, pagination: OffsetPaginationInput): ToolTypeOffsetPaginated!
  caseStudy(id: ID!): CaseStudyType!
  contactRequest(id: ID!): ContactRequestType!
  caseStudies(filters: CaseStudyFilter, order: CaseStudyOrder, pagination: OffsetPaginationInput): CaseStudyTypeOffsetPaginated!
  contactRequests(filters: ContactRequestFilter, order: ContactRequestOrder, pagination: OffsetPaginationInput): ContactRequestTypeOffsetPaginated!
  enums: AppEnumCollection!
}

"""Model representing question within a catalog."""
type QuestionType {
  id: ID!
  catalogId: ID!
  questionType: QuestionTypeEnum!
  title: String!
  description: String!
  order: Int!
  labelNa: String!
  label1: String!
  label2: String!
  label3: String!
  label4: String!
  options: [CheckboxOptionType!]!
}

enum QuestionTypeEnum {
  ORDINAL
  CHECKBOX
}

"""Model representing tool's selection of question and its answer."""
type ToolAnswerType {
  id: ID!
  toolId: ID!
  questionId: ID!
  description: String!
  ordinalValue: OrdinalTypeEnum
  selectedOptions: [CheckboxOptionType!]!
}

"""Model representing tool."""
input ToolFilter {
  id: ID
  catalogId: IDBaseFilterLookup
  AND: ToolFilter
  OR: ToolFilter
  NOT: ToolFilter
  DISTINCT: Boolean
}

input ToolOrder {
  id: Ordering
}

"""Model representing tool."""
type ToolType {
  id: ID!
  catalog: CatalogType!
  name: String!
  tagline: String!
  description: String!
  videoLink: String
  toolLink: String
  logo: DjangoFileType
  answers: [ToolAnswerType!]!
}

type ToolTypeOffsetPaginated {
  pageInfo: OffsetPaginationInfo!

  """Total count of existing results."""
  totalCount: Int!

  """List of paginated results."""
  results: [ToolType!]!
}