# Generated by Django 5.2.9 on 2026-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='External case study URL'),
        ),
    ]
