# Generated by Django 5.2.9 on 2026-03-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_casestudy_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=models.TextField(max_length=320),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='link',
            field=models.URLField(default='', verbose_name='External case study URL'),
            preserve_default=False,
        ),
    ]
