# Generated by Django 5.2.9 on 2026-04-03 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_casestudy_content_alter_casestudy_link'),
        ('tool_picker', '0004_alter_checkboxoption_order_alter_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='cover_image',
            field=models.ImageField(default='', upload_to='case_studies/', verbose_name='Case Study Cover Image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('national_society', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_demo_tool', to='tool_picker.tool', verbose_name='Related Tool')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
