# Generated by Django 5.2.9 on 2026-04-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_steerco',
            field=models.BooleanField(default=False),
        ),
    ]
