# Generated by Django 5.2.9 on 2026-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_steerco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_steerco',
            field=models.BooleanField(default=False, help_text='Designates that this user has full administrative access to manage all users, catalogs, and tools.'),
        ),
    ]
