apiVersion: v2
name: nrcs-website-backend
description: "Helm chart for NRCs website backend"
type: application
version: 0.1.0-SET-BY-CICD
appVersion: "1.16.0"
sources:
  - https://github.com/toggle-corp/nrcs-backend


dependencies:
  - name: toggle-django-helm
    alias: app
    version: 0.2.0
    repository: "oci://ghcr.io/toggle-corp"
