apiVersion: v2
name: rc-select-helm
description: A Helm chart for rc select
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: toggle-django-helm
    alias: app
    version: 0.2.5
    repository: oci://ghcr.io/toggle-corp
