# Generated by Django 5.2.9 on 2026-02-02 08:15

import apps.tool_picker.models
import django.core.validators
import django.db.models.deletion
import django_choices_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('show_in_help_me_choose', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question_type', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Ordinal'), (20, 'Checkbox')], choices_enum=apps.tool_picker.models.QuestionTypeEnum)),
                ('title', models.CharField(max_length=500)),
                ('short_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('label_na', models.TextField(blank=True, default='N/A')),
                ('label_1', models.TextField(blank=True, default='1')),
                ('label_2', models.TextField(blank=True, default='2')),
                ('label_3', models.TextField(blank=True, default='3')),
                ('label_4', models.TextField(blank=True, default='4')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tool_picker.catalog')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['catalog', 'order'],
                'abstract': False,
                'unique_together': {('catalog', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tool_picker.question')),
            ],
            options={
                'ordering': ['question', 'order'],
                'abstract': False,
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CheckboxQuestionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Checkbox Question (Bulk Edit)',
                'verbose_name_plural': 'Checkbox Questions (Bulk Edit)',
                'ordering': ['-id'],
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tool_picker.question',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('video_link', models.CharField(blank=True, null=True)),
                ('tool_link', models.CharField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tool_picker.catalog')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['catalog', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tool_picker.catalog')),
            ],
            options={
                'verbose_name': 'User Submission',
                'verbose_name_plural': 'User Submissions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('ordinal_value', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'n/a'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], choices_enum=apps.tool_picker.models.OrdinalTypeEnum, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_answers', to='tool_picker.question')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='tool_answers', to='tool_picker.checkboxoption')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tool_picker.tool')),
            ],
            options={
                'verbose_name': 'Tool Answer',
                'verbose_name_plural': 'Tool Answers',
                'ordering': ['-id'],
                'abstract': False,
                'unique_together': {('tool', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_value', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(100, 'n/a'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], choices_enum=apps.tool_picker.models.OrdinalTypeEnum, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='tool_picker.question')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='user_answers', to='tool_picker.checkboxoption')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tool_picker.usersubmission')),
            ],
            options={
                'verbose_name': 'User Answer',
                'verbose_name_plural': 'User Answers',
                'ordering': ['question__order'],
                'abstract': False,
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score', models.FloatField(help_text='Proximity score - lower is better (closer match)')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='tool_picker.tool')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tool_picker.usersubmission')),
            ],
            options={
                'verbose_name': 'Recommendation Result',
                'verbose_name_plural': 'Recommendation Results',
                'ordering': ['submission', 'rank'],
                'abstract': False,
                'unique_together': {('submission', 'rank')},
            },
        ),
    ]
