# Generated by Django 5.2.9 on 2025-12-30 09:59

import apps.tool_picker.models
import django.core.validators
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['question', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question_type', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Ordinal'), (20, 'Checkbox')], choices_enum=apps.tool_picker.models.QuestionTypeEnum)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('label_na', models.CharField(blank=True, default='N/A', max_length=100)),
                ('label_1', models.CharField(blank=True, default='1', max_length=100)),
                ('label_2', models.CharField(blank=True, default='2', max_length=100)),
                ('label_3', models.CharField(blank=True, default='3', max_length=100)),
                ('label_4', models.CharField(blank=True, default='4', max_length=100)),
            ],
            options={
                'ordering': ['catalog', 'order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('video_link', models.TextField(blank=True, null=True)),
                ('tool_link', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logs/', verbose_name='Logo')),
            ],
            options={
                'ordering': ['catalog', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('ordinal_value', django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(10, 'n/a'), (11, '1'), (12, '2'), (13, '3'), (14, '4')], choices_enum=apps.tool_picker.models.OrdinalTypeEnum, null=True)),
            ],
            options={
                'verbose_name': 'Tool Answer',
                'verbose_name_plural': 'Tool Answers',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
