# Generated by Django 5.2.9 on 2026-01-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='show_in_help_me_choose',
            field=models.BooleanField(default=False),
        ),
    ]
