# Generated by Django 5.2.9 on 2026-02-19 05:31

import apps.tool_picker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='video_link',
            field=models.URLField(blank=True, null=True, validators=[apps.tool_picker.models.validate_url]),
        ),
    ]
