# Generated by Django 5.2.9 on 2026-02-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0002_alter_tool_video_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_catalog_order',
        ),
    ]
