# Generated by Django 5.2.9 on 2026-02-10 11:00

import apps.tool_picker.models
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0002_catalog_show_in_help_me_choose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feature_category', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Configuration'), (20, 'Beneficiary Registration'), (30, 'Distribution Management'), (40, 'Feedback and Surveys'), (50, 'Data Management'), (60, 'Reporting and Analytics')], choices_enum=apps.tool_picker.models.ToolFeature.FeatureCategoryEnum, default='None')),
                ('description', models.TextField(null=True)),
                ('cash_RTM_code', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sector_owners', models.ManyToManyField(blank=True, related_name='sector_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_sectors',
            field=models.ManyToManyField(blank=True, related_name='tool_sectors', to='tool_picker.sector'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_features',
            field=models.ManyToManyField(blank=True, related_name='tool_features', to='tool_picker.toolfeature'),
        ),
    ]
