# Generated by Django 5.2.9 on 2026-01-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkboxquestionproxy',
            options={'ordering': ['-id'], 'verbose_name': 'Checkbox Question (Bulk Edit)', 'verbose_name_plural': 'Checkbox Questions (Bulk Edit)'},
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='video_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
