# Generated by Django 5.2.9 on 2026-02-10 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0003_toolfeature_sector_tool_tool_sectors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_owners',
            field=models.ManyToManyField(blank=True, related_name='tool_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
