# Generated by Django 5.2.9 on 2026-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0003_remove_question_unique_catalog_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxoption',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
