# Generated by Django 5.2.9 on 2026-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0004_usersubmission_useranswer_recommendationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
