# Generated by Django 5.2.9 on 2026-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0004_alter_checkboxoption_order_alter_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='catalogs',
            field=models.ManyToManyField(help_text='After adding or updating a catalog, the related questions are automatically populated to this tool.', related_name='tool_catalogs', to='tool_picker.catalog'),
        ),
    ]
