# Generated by Django 5.2.9 on 2026-04-17 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0005_alter_tool_catalogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='catalog_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
