# Generated by Django 5.2.9 on 2026-04-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0006_catalog_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='owners',
            new_name='catalog_owners',
        ),
    ]
