# Generated by Django 5.2.9 on 2026-04-17 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0007_rename_owners_catalog_catalog_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='catalog_owners',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tool_owners',
        ),
        migrations.AddField(
            model_name='catalog',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='catalog_owners', to=settings.AUTH_USER_MODEL, verbose_name='catalog owners'),
        ),
        migrations.AddField(
            model_name='tool',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='tool_owners', to=settings.AUTH_USER_MODEL, verbose_name='Tool owners'),
        ),
    ]
