name: Python check

on:
  pull_request:

jobs:
  pre_commit_checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - uses: astral-sh/setup-uv@v5
        with:
          python-version-file: .python-version
      
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup uv python environment
        run: uv venv

      - name: uv lock check
        run: uv lock --locked --offline

      - name: uv sync
        run: uv sync --all-groups --all-extras

      - uses: pre-commit/action@main
